#!/usr/bin/env python3
from pathlib import Path
root=Path(__file__).resolve().parents[1]
source=root/'source/sabri-membership-core/includes/class-smc-events.php'
s=source.read_text()
old="""\t\t$consumer = sanitize_key( $consumer );\n\t\t$event_id = sanitize_text_field( (string) $event['event_id'] );\n\t\t$dedupe = hash( 'sha256', $consumer . '|' . $event_id );\n\t\t$now = current_time( 'mysql', true );\n\t\t$inserted = $wpdb->query(\n\t\t\t$wpdb->prepare(\n\t\t\t\t\"INSERT IGNORE INTO {$wpdb->prefix}smc_event_inbox (consumer,event_id,dedupe_hash,status,created_at,updated_at) VALUES (%s,%s,%s,'processing',%s,%s)\",\n\t\t\t\t$consumer,\n\t\t\t\t$event_id,\n\t\t\t\t$dedupe,\n\t\t\t\t$now,\n\t\t\t\t$now\n\t\t\t)\n\t\t);\n\t\tif ( 0 === $inserted ) {\n\t\t\t$status = $wpdb->get_var( $wpdb->prepare( \"SELECT status FROM {$wpdb->prefix}smc_event_inbox WHERE consumer=%s AND dedupe_hash=%s LIMIT 1\", $consumer, $dedupe ) );\n\t\t\treturn 'processed' === $status;\n\t\t}\n\t\t$result = call_user_func( $callback, $event );\n\t\tif ( true !== $result ) {\n\t\t\t$wpdb->delete( $wpdb->prefix . 'smc_event_inbox', array( 'consumer' => $consumer, 'dedupe_hash' => $dedupe ), array( '%s', '%s' ) );\n\t\t\treturn false;\n\t\t}\n\t\t$updated = $wpdb->query( $wpdb->prepare( \"UPDATE {$wpdb->prefix}smc_event_inbox SET status='processed',processed_at=%s,updated_at=%s WHERE consumer=%s AND dedupe_hash=%s AND status='processing'\", $now, $now, $consumer, $dedupe ) );\n\t\treturn 1 === $updated;\n"""
new="""\t\t$consumer = sanitize_key( $consumer );\n\t\t$event_id = sanitize_text_field( (string) $event['event_id'] );\n\t\tif ( '' === $consumer || '' === $event_id ) { return false; }\n\t\t$now = current_time( 'mysql', true );\n\t\t$inserted = $wpdb->query(\n\t\t\t$wpdb->prepare(\n\t\t\t\t\"INSERT IGNORE INTO {$wpdb->prefix}smc_event_inbox (consumer,event_id,status,attempts,received_at,updated_at) VALUES (%s,%s,'processing',1,%s,%s)\",\n\t\t\t\t$consumer,\n\t\t\t\t$event_id,\n\t\t\t\t$now,\n\t\t\t\t$now\n\t\t\t)\n\t\t);\n\t\tif ( 0 === $inserted ) {\n\t\t\t$status = $wpdb->get_var( $wpdb->prepare( \"SELECT status FROM {$wpdb->prefix}smc_event_inbox WHERE consumer=%s AND event_id=%s LIMIT 1\", $consumer, $event_id ) );\n\t\t\treturn 'processed' === $status;\n\t\t}\n\t\tif ( 1 !== $inserted ) { return false; }\n\t\t$result = call_user_func( $callback, $event );\n\t\tif ( true !== $result ) {\n\t\t\t$wpdb->delete( $wpdb->prefix . 'smc_event_inbox', array( 'consumer' => $consumer, 'event_id' => $event_id ), array( '%s', '%s' ) );\n\t\t\treturn false;\n\t\t}\n\t\t$updated = $wpdb->query( $wpdb->prepare( \"UPDATE {$wpdb->prefix}smc_event_inbox SET status='processed',processed_at=%s,updated_at=%s WHERE consumer=%s AND event_id=%s AND status='processing'\", $now, $now, $consumer, $event_id ) );\n\t\treturn 1 === $updated;\n"""
if new not in s:
    if old not in s: raise SystemExit('round6 inbox consume block not found')
    source.write_text(s.replace(old,new,1))

contract=root/'qa/second-fresh-review-contract.mjs'
c=contract.read_text()
if "const events=" not in c:
    c=c.replace("const security=fs.readFileSync('source/sabri-membership-core/includes/class-smc-security.php','utf8');\n", "const security=fs.readFileSync('source/sabri-membership-core/includes/class-smc-security.php','utf8');\nconst events=fs.readFileSync('source/sabri-membership-core/includes/class-smc-events.php','utf8');\nconst installer=fs.readFileSync('source/sabri-membership-core/includes/class-smc-installer.php','utf8');\n")
if "event inbox consumer uses canonical schema columns" not in c:
    c=c.replace("console.log(`Second fresh static complete; failures: ${failed}`); process.exit(failed?1:0);", "pass('event inbox consumer uses canonical schema columns', events.includes('(consumer,event_id,status,attempts,received_at,updated_at)') && !events.includes('(consumer,event_id,dedupe_hash,status,created_at,updated_at)'));\npass('event inbox idempotency matches unique consumer-event schema', installer.includes('UNIQUE KEY consumer_event (consumer,event_id)') && events.includes('WHERE consumer=%s AND event_id=%s'));\nconsole.log(`Second fresh static complete; failures: ${failed}`); process.exit(failed?1:0);")
contract.write_text(c)
