#!/usr/bin/env python3
from pathlib import Path
root=Path(__file__).resolve().parents[1]
source=root/'source/sabri-membership-core/includes/class-smc-advanced-trust-2026.php'
hard=root/'qa/advanced-trust-review-hardening-runtime.php'
s=source.read_text()
old="""\tpublic static function set_containment_state( $user_id, $state, $actor_id = 0, $reason = '' ) {\n\t\t$user_id = absint( $user_id );\n\t\t$state = sanitize_key( $state );\n\t\tif ( ! in_array( $state, array( 'clear', 'security_recovery_required', 'contained' ), true ) ) {\n\t\t\treturn new WP_Error( 'smc_containment_state', __( 'Unsupported security containment state.', 'sabri-membership-core' ) );\n\t\t}\n\t\t$actor_id = absint( $actor_id );\n\t\t$authorized = $actor_id > 0 ? self::actor_is_current( $actor_id, 'smc_manage_membership' ) && SMC_Security::session_is_verified( $actor_id ) : (bool) apply_filters( 'smc_file24_security_containment_authorized', false, $user_id, $state, $reason );\n\t\tif ( ! $authorized ) { return new WP_Error( 'smc_containment_authorization', __( 'Security containment requires authorized membership/security governance.', 'sabri-membership-core' ) ); }\n\t\t$record = array( 'state' => $state, 'updated_at' => time(), 'actor_id' => $actor_id, 'reason' => sanitize_text_field( $reason ) );\n\t\tif ( ! self::write_user_meta_verified( $user_id, self::CONTAINMENT_META, $record ) ) {\n\t\t\treturn new WP_Error( 'smc_containment_store', __( 'Security containment state could not be persisted safely.', 'sabri-membership-core' ) );\n\t\t}\n\t\tif ( ! SMC_Security::revoke_all_sessions( $user_id, 'security_containment_' . $state ) ) {\n\t\t\treturn new WP_Error( 'smc_containment_sessions', __( 'Security containment could not invalidate existing sessions.', 'sabri-membership-core' ) );\n\t\t}\n\t\tif ( ! self::write_user_meta_verified( $user_id, '_smc_revalidation_required_at', time() + 1 ) ) {\n\t\t\treturn new WP_Error( 'smc_containment_revalidation', __( 'Security containment could not require a fresh session challenge.', 'sabri-membership-core' ) );\n\t\t}\n\t\tif ( ! SMC_Security::audit( 'security_containment_changed', $user_id, array( 'state' => $state, 'reason' => $record['reason'] ) ) ) {\n\t\t\treturn new WP_Error( 'smc_containment_audit', __( 'Security containment change could not be audited.', 'sabri-membership-core' ) );\n\t\t}\n\t\tif ( false === self::bump_revocation_epoch( $user_id, 'security_containment_changed' ) ) {\n\t\t\treturn new WP_Error( 'smc_containment_revocation', __( 'Security containment change could not be propagated safely.', 'sabri-membership-core' ) );\n\t\t}\n\t\treturn $record;\n\t}\n"""
new="""\tpublic static function set_containment_state( $user_id, $state, $actor_id = 0, $reason = '' ) {\n\t\t$user_id = absint( $user_id );\n\t\t$state = sanitize_key( $state );\n\t\tif ( ! in_array( $state, array( 'clear', 'security_recovery_required', 'contained' ), true ) ) {\n\t\t\treturn new WP_Error( 'smc_containment_state', __( 'Unsupported security containment state.', 'sabri-membership-core' ) );\n\t\t}\n\t\t$actor_id = absint( $actor_id );\n\t\t$authorized = $actor_id > 0 ? self::actor_is_current( $actor_id, 'smc_manage_membership' ) && SMC_Security::session_is_verified( $actor_id ) : (bool) apply_filters( 'smc_file24_security_containment_authorized', false, $user_id, $state, $reason );\n\t\tif ( ! $authorized ) { return new WP_Error( 'smc_containment_authorization', __( 'Security containment requires authorized membership/security governance.', 'sabri-membership-core' ) ); }\n\t\tif ( ! self::begin_transition_hold( $user_id, 'containment', $state, $actor_id ) ) { return new WP_Error( 'smc_containment_hold', __( 'Security containment could not enter a fail-closed transition hold.', 'sabri-membership-core' ) ); }\n\t\t$record = array( 'state' => $state, 'updated_at' => time(), 'actor_id' => $actor_id, 'reason' => sanitize_text_field( $reason ) );\n\t\tif ( ! self::write_user_meta_verified( $user_id, self::CONTAINMENT_META, $record ) ) { return new WP_Error( 'smc_containment_store', __( 'Security containment state could not be persisted safely.', 'sabri-membership-core' ) ); }\n\t\tif ( ! SMC_Security::revoke_all_sessions( $user_id, 'security_containment_' . $state ) ) { return new WP_Error( 'smc_containment_sessions', __( 'Security containment could not invalidate existing sessions.', 'sabri-membership-core' ) ); }\n\t\tif ( ! self::write_user_meta_verified( $user_id, '_smc_revalidation_required_at', time() + 1 ) ) { return new WP_Error( 'smc_containment_revalidation', __( 'Security containment could not require a fresh session challenge.', 'sabri-membership-core' ) ); }\n\t\tif ( ! SMC_Security::audit( 'security_containment_changed', $user_id, array( 'state' => $state, 'reason' => $record['reason'] ) ) ) { return new WP_Error( 'smc_containment_audit', __( 'Security containment change could not be audited.', 'sabri-membership-core' ) ); }\n\t\tif ( false === self::bump_revocation_epoch( $user_id, 'security_containment_changed' ) ) { return new WP_Error( 'smc_containment_revocation', __( 'Security containment change could not be propagated safely.', 'sabri-membership-core' ) ); }\n\t\tif ( ! self::clear_transition_hold( $user_id ) ) { return new WP_Error( 'smc_containment_hold_clear', __( 'Security containment remains fail-closed because its transition hold could not be cleared.', 'sabri-membership-core' ) ); }\n\t\treturn $record;\n\t}\n"""
if old not in s: raise SystemExit('round4 containment block not found')
s=s.replace(old,new,1)
old2="""\tpublic static function set_continuity_state( $user_id, $state, $actor_id = 0, $reason = '' ) {\n\t\t$user_id = absint( $user_id ); $state = sanitize_key( $state );\n\t\tif ( ! in_array( $state, array( 'active', 'dormant', 'deceased', 'permanently_inactive' ), true ) ) { return new WP_Error( 'smc_continuity_state', __( 'Unsupported continuity state.', 'sabri-membership-core' ) ); }\n\t\t$actor_id = absint( $actor_id );\n\t\tif ( ! self::actor_is_current( $actor_id, 'smc_manage_membership' ) || ! SMC_Security::session_is_verified( $actor_id ) ) { return new WP_Error( 'smc_continuity_authorization', __( 'Continuity-state changes require authorized membership governance and fresh security challenge.', 'sabri-membership-core' ) ); }\n\t\t$record = array( 'state' => $state, 'updated_at' => time(), 'actor_id' => $actor_id, 'reason' => sanitize_text_field( $reason ), 'authorship_preserved' => true );\n\t\tif ( ! self::write_user_meta_verified( $user_id, self::CONTINUITY_META, $record ) ) { return new WP_Error( 'smc_continuity_store', __( 'Continuity state could not be persisted safely.', 'sabri-membership-core' ) ); }\n\t\tif ( ! SMC_Security::revoke_all_sessions( $user_id, 'continuity_state_' . $state ) ) { return new WP_Error( 'smc_continuity_sessions', __( 'Continuity change could not invalidate existing sessions.', 'sabri-membership-core' ) ); }\n\t\tif ( ! self::write_user_meta_verified( $user_id, '_smc_revalidation_required_at', time() + 1 ) ) { return new WP_Error( 'smc_continuity_revalidation', __( 'Continuity change could not require a fresh challenge.', 'sabri-membership-core' ) ); }\n\t\tif ( ! SMC_Security::audit( 'continuity_state_changed', $user_id, array( 'state' => $state, 'reason' => $record['reason'] ) ) ) { return new WP_Error( 'smc_continuity_audit', __( 'Continuity change could not be audited.', 'sabri-membership-core' ) ); }\n\t\tif ( false === self::bump_revocation_epoch( $user_id, 'continuity_state_changed' ) ) { return new WP_Error( 'smc_continuity_revocation', __( 'Continuity change could not be propagated safely.', 'sabri-membership-core' ) ); }\n\t\treturn $record;\n\t}\n"""
new2="""\tpublic static function set_continuity_state( $user_id, $state, $actor_id = 0, $reason = '' ) {\n\t\t$user_id = absint( $user_id ); $state = sanitize_key( $state );\n\t\tif ( ! in_array( $state, array( 'active', 'dormant', 'deceased', 'permanently_inactive' ), true ) ) { return new WP_Error( 'smc_continuity_state', __( 'Unsupported continuity state.', 'sabri-membership-core' ) ); }\n\t\t$actor_id = absint( $actor_id );\n\t\tif ( ! self::actor_is_current( $actor_id, 'smc_manage_membership' ) || ! SMC_Security::session_is_verified( $actor_id ) ) { return new WP_Error( 'smc_continuity_authorization', __( 'Continuity-state changes require authorized membership governance and fresh security challenge.', 'sabri-membership-core' ) ); }\n\t\tif ( ! self::begin_transition_hold( $user_id, 'continuity', $state, $actor_id ) ) { return new WP_Error( 'smc_continuity_hold', __( 'Continuity change could not enter a fail-closed transition hold.', 'sabri-membership-core' ) ); }\n\t\t$record = array( 'state' => $state, 'updated_at' => time(), 'actor_id' => $actor_id, 'reason' => sanitize_text_field( $reason ), 'authorship_preserved' => true );\n\t\tif ( ! self::write_user_meta_verified( $user_id, self::CONTINUITY_META, $record ) ) { return new WP_Error( 'smc_continuity_store', __( 'Continuity state could not be persisted safely.', 'sabri-membership-core' ) ); }\n\t\tif ( ! SMC_Security::revoke_all_sessions( $user_id, 'continuity_state_' . $state ) ) { return new WP_Error( 'smc_continuity_sessions', __( 'Continuity change could not invalidate existing sessions.', 'sabri-membership-core' ) ); }\n\t\tif ( ! self::write_user_meta_verified( $user_id, '_smc_revalidation_required_at', time() + 1 ) ) { return new WP_Error( 'smc_continuity_revalidation', __( 'Continuity change could not require a fresh challenge.', 'sabri-membership-core' ) ); }\n\t\tif ( ! SMC_Security::audit( 'continuity_state_changed', $user_id, array( 'state' => $state, 'reason' => $record['reason'] ) ) ) { return new WP_Error( 'smc_continuity_audit', __( 'Continuity change could not be audited.', 'sabri-membership-core' ) ); }\n\t\tif ( false === self::bump_revocation_epoch( $user_id, 'continuity_state_changed' ) ) { return new WP_Error( 'smc_continuity_revocation', __( 'Continuity change could not be propagated safely.', 'sabri-membership-core' ) ); }\n\t\tif ( ! self::clear_transition_hold( $user_id ) ) { return new WP_Error( 'smc_continuity_hold_clear', __( 'Continuity state remains fail-closed because its transition hold could not be cleared.', 'sabri-membership-core' ) ); }\n\t\treturn $record;\n\t}\n"""
if old2 not in s: raise SystemExit('round4 continuity block not found')
s=s.replace(old2,new2,1)
anchor="""\tpublic static function protected_actions_allowed( $user_id ) {\n\t\t$user_id = absint( $user_id );\n"""
repl="""\tpublic static function protected_actions_allowed( $user_id ) {\n\t\t$user_id = absint( $user_id );\n\t\tif ( metadata_exists( 'user', $user_id, '_smc_trust_transition_hold_v1' ) ) { return false; }\n"""
if anchor not in s: raise SystemExit('round4 protected anchor not found')
s=s.replace(anchor,repl,1)
helper_anchor="""\tprivate static function write_user_meta_verified( $user_id, $key, $value ) {\n"""
helpers="""\tprivate static function begin_transition_hold( $user_id, $kind, $target_state, $actor_id ) {\n\t\t$hold = array( 'kind' => sanitize_key( $kind ), 'target_state' => sanitize_key( $target_state ), 'actor_id' => absint( $actor_id ), 'started_at' => time() );\n\t\treturn self::write_user_meta_verified( absint( $user_id ), '_smc_trust_transition_hold_v1', $hold );\n\t}\n\n\tprivate static function clear_transition_hold( $user_id ) {\n\t\tdelete_user_meta( absint( $user_id ), '_smc_trust_transition_hold_v1' );\n\t\treturn ! metadata_exists( 'user', absint( $user_id ), '_smc_trust_transition_hold_v1' );\n\t}\n\n"""+helper_anchor
if helper_anchor not in s: raise SystemExit('round4 helper anchor not found')
s=s.replace(helper_anchor,helpers,1); source.write_text(s)
h=hard.read_text()
anchorh="$fail_revoke=true;$r=SMC_Advanced_Trust_2026::set_containment_state(7,'contained',1,'x');t('containment session revoke failure fails closed',is_wp_error($r));$fail_revoke=false;\n"
insert=anchorh+"$fail_revoke=false;SMC_Advanced_Trust_2026::set_containment_state(12,'contained',1,'pre');$fail_revoke=true;$r=SMC_Advanced_Trust_2026::set_containment_state(12,'clear',1,'recover');t('containment relaxation failure remains synchronously blocked',is_wp_error($r)&&!SMC_Advanced_Trust_2026::protected_actions_allowed(12));$fail_revoke=false;SMC_Advanced_Trust_2026::set_containment_state(12,'clear',1,'recover');\nSMC_Advanced_Trust_2026::set_continuity_state(13,'dormant',1,'pre');$fail_revoke=true;$r=SMC_Advanced_Trust_2026::set_continuity_state(13,'active',1,'restore');t('continuity relaxation failure remains synchronously blocked',is_wp_error($r)&&!SMC_Advanced_Trust_2026::protected_actions_allowed(13));$fail_revoke=false;SMC_Advanced_Trust_2026::set_continuity_state(13,'active',1,'restore');\n"
if anchorh not in h: raise SystemExit('round4 test anchor not found')
h=h.replace(anchorh,insert,1); hard.write_text(h)
