<?php
error_reporting(E_ALL);
define('ABSPATH',__DIR__.'/');define('MINUTE_IN_SECONDS',60);define('DAY_IN_SECONDS',86400);define('YEAR_IN_SECONDS',31536000);define('ARRAY_A','ARRAY_A');define('SMC_VERSION','1.2.40');
$meta=[];$options=[];$filters=[];$actions=[];$apps=[];$caps=[1=>['manage_options'=>true,'smc_manage_membership'=>true,'smc_finalize_verification'=>true],2=>['manage_options'=>true,'smc_manage_membership'=>true,'smc_finalize_verification'=>true]];$current_user_id=1;$guardian_id=11;
class WP_Error{public $code;function __construct($c,$m=''){$this->code=$c;}}function is_wp_error($v){return $v instanceof WP_Error;}function __($s,$d=null){return $s;}function absint($v){return abs((int)$v);}function sanitize_key($v){return strtolower(preg_replace('/[^a-z0-9_\-]/','',(string)$v));}function sanitize_text_field($v){return trim(strip_tags((string)$v));}function get_current_user_id(){global $current_user_id;return $current_user_id;}function get_userdata($id){return $id>0?(object)['ID'=>$id]:false;}function user_can($u,$cap){global $caps;$id=is_object($u)?(int)$u->ID:(int)$u;return !empty($caps[$id][$cap]);}function current_user_can($cap){return user_can(get_userdata(get_current_user_id()),$cap);}function get_user_meta($id,$key='',$single=false){global $meta;if($key==='')return $meta[$id]??[];return $meta[$id][$key]??($single?'':[]);}function update_user_meta($id,$key,$value){global $meta;$meta[$id][$key]=$value;return true;}function delete_user_meta($id,$key){global $meta;unset($meta[$id][$key]);return true;}function metadata_exists($t,$id,$key){global $meta;return array_key_exists($key,$meta[$id]??[]);}function add_action($a,$b,$p=10,$n=1){return true;}function add_filter($a,$b,$p=10,$n=1){return true;}function apply_filters($tag,$value,...$args){global $filters;return isset($filters[$tag])&&is_callable($filters[$tag])?$filters[$tag]($value,...$args):$value;}function do_action($tag,...$args){global $actions;$actions[]=[$tag,$args];}function wp_generate_uuid4(){static $i=0;return sprintf('00000000-0000-4000-8000-%012d',++$i);}function wp_salt($s='auth'){return 'salt-'.$s;}function wp_json_encode($v,$f=0){return json_encode($v,$f);}function get_option($k,$d=false){global $options;return $options[$k]??$d;}function update_option($k,$v,$autoload=false){global $options;$options[$k]=$v;return true;}function add_option($k,$v,$dep='',$autoload='yes'){global $options;if(array_key_exists($k,$options))return false;$options[$k]=$v;return true;}function delete_option($k){global $options;unset($options[$k]);return true;}function smc_is_founder($id){return (int)$id===1;}function smc_is_institutional_ai($id){return false;}function smc_policy(){return ['version'=>'2026-08-05-v2.1'];}function smc_application($id){global $apps;return $apps[$id]??false;}function smc_age_from_dob($dob){try{$d=new DateTimeImmutable($dob,new DateTimeZone('UTC'));$n=new DateTimeImmutable('today',new DateTimeZone('UTC'));return $d>$n?false:$d->diff($n)->y;}catch(Throwable $e){return false;}}function smc_effective_minimum_age($g,$c=''){return $g==='female'?12:($g==='male'?15:false);}
class DB{public $prefix='wp_';public $users='wp_users';public $approved_at;public function __construct(){$this->approved_at=gmdate('Y-m-d H:i:s');}function prepare($q,...$a){return $q;}function get_var($q){global $guardian_id;if(strpos($q,'GET_LOCK')!==false||strpos($q,'RELEASE_LOCK')!==false)return 1;if(strpos($q,'smc_guardian_consents')!==false)return $guardian_id;if(strpos($q,'smc_role_grants')!==false||strpos($q,'smc_applications')!==false)return $this->approved_at;return 1;}function get_col($q){return [];}function get_results($q,$m){return [];}}$wpdb=new DB();
class SMC_Security{static function revoke_all_sessions($id,$r=''){return true;}static function audit($a,$id=0,$d=[]){return true;}static function subject_hash($id){return hash('sha256','s'.$id);}static function blind_index($v,$p){return hash_hmac('sha256',$p.'|'.$v,'k');}static function decrypt($v,$p,$c=[]){return $v;}}
class SMC_Contracts{static function assertions($id){global $apps;$app=$apps[$id]??null;return ['application_exists'=>(bool)$app,'institutional_account'=>false,'status'=>'approved','approved'=>true,'suspended'=>false,'eligible'=>true,'identity_documents_current'=>true,'phone_verified'=>true,'email_verified'=>true,'guardian_verified'=>true,'professional_verified'=>true,'public_profile_allowed'=>true];}static function guardian_verified($id){return true;}}
class SMC_CF01_Contract{static function ensure_subject_uuid($id){return 'uuid-'.$id;}}
require __DIR__.'/../source/sabri-membership-core/includes/class-smc-advanced-trust-2026.php';
$T=[];function t($n,$ok){global $T;$T[]=[$n,(bool)$ok];}
$fresh_file02=fn($b,$u)=>['owner'=>'file02','contract_version'=>'1.0.0','level'=>3,'method'=>'passkey','passkey_asserted'=>true,'hardware_backed'=>true,'verified_at'=>time()+2];
// R1: declared break-glass policy must reject absence of File02 assurance and require hardware-backed File02 step-up.
$no_auth=SMC_Advanced_Trust_2026::open_break_glass(7,1,'test');t('break-glass rejects missing File02 authentication assurance',is_wp_error($no_auth));
$filters['smc_file02_authentication_assurance_v1']=$fresh_file02;$bg=SMC_Advanced_Trust_2026::open_break_glass(7,1,'test');$current_user_id=2;$ok2=is_array($bg)&&SMC_Advanced_Trust_2026::approve_break_glass($bg['id'],2);$current_user_id=1;$tok=$ok2?SMC_Advanced_Trust_2026::consume_break_glass($bg['id'],1):false;t('break-glass accepts dual current hardware-backed File02 approvers',is_array($tok)&&!empty($tok['authorized']));unset($filters['smc_file02_authentication_assurance_v1']);
// R4: legacy boolean cannot authorize File24 containment; typed fresh subject/state claim can.
$filters['smc_file24_security_containment_authorized']=fn()=>true;$bad=SMC_Advanced_Trust_2026::set_containment_state(8,'contained',0,'risk');t('legacy bare File24 boolean rejected',is_wp_error($bad));unset($filters['smc_file24_security_containment_authorized']);$filters['smc_file24_security_containment_authorization_v1']=fn($v,$u,$st,$r)=>['owner'=>'file24','contract_version'=>'1.0.0','authorized'=>true,'subject'=>'uuid-'.$u,'state'=>$st,'asserted_at'=>time()];$good=SMC_Advanced_Trust_2026::set_containment_state(8,'contained',0,'risk');t('typed File24 containment accepted',is_array($good)&&$good['state']==='contained');unset($filters['smc_file24_security_containment_authorization_v1']);
// R3: revocation event boundary exposes opaque subject in both payload and hook argument.
$actions=[];$rev=SMC_Advanced_Trust_2026::bump_revocation_epoch(7,'test');$opaque=false;foreach($actions as $a){if($a[0]==='smc_trust_revocation_invalidated')$opaque=($a[1][0]==='uuid-7'&&!array_key_exists('user_id',$a[1][1]));}t('revocation hook is opaque end-to-end',is_array($rev)&&$opaque);
// R5: impossible VC chronology must fail even when each timestamp is individually fresh.
$filters['smc_external_verifiable_credentials_v1']=fn($v,$u)=>[['contract_version'=>'1.0.0','owner'=>'credential_adapter','subject'=>'uuid-'.$u,'issuer'=>'issuer','type'=>'license','verified'=>true,'proof_reference'=>'proof','verified_at'=>time()-120,'issued_at'=>time()-60,'expires_at'=>time()+600]];t('VC issued after verification is rejected',count(SMC_Advanced_Trust_2026::verifiable_credentials(7))===0);$filters['smc_external_verifiable_credentials_v1']=fn($v,$u)=>[['contract_version'=>'1.0.0','owner'=>'credential_adapter','subject'=>'uuid-'.$u,'issuer'=>'issuer','type'=>'license','verified'=>true,'proof_reference'=>'proof','verified_at'=>time()-60,'issued_at'=>time()-120,'expires_at'=>time()+600]];t('coherent fresh VC accepted',count(SMC_Advanced_Trust_2026::verifiable_credentials(7))===1);unset($filters['smc_external_verifiable_credentials_v1']);
// R6: delegation requires File02 step-up and ends immediately when its grantor loses the governing capability.
$filters['smc_file02_authentication_assurance_v1']=$fresh_file02;$current_user_id=2;$d=SMC_Advanced_Trust_2026::grant_delegated_authority(9,2,['membership_support'],time()+900);$current_user_id=1;t('delegation active while grantor current and File02-authenticated',is_array($d)&&SMC_Advanced_Trust_2026::has_delegated_scope(9,'membership_support'));$caps[2]['smc_manage_membership']=false;t('delegation suspended when grantor authority is lost',!SMC_Advanced_Trust_2026::has_delegated_scope(9,'membership_support'));$caps[2]['smc_manage_membership']=true;unset($filters['smc_file02_authentication_assurance_v1']);
// R7: a once-approved privileged actor cannot remain a valid emergency approver after entering a protected hold.
$filters['smc_file02_authentication_assurance_v1']=$fresh_file02;$current_user_id=1;$bg2=SMC_Advanced_Trust_2026::open_break_glass(10,1,'stale approver');$current_user_id=2;$ap=SMC_Advanced_Trust_2026::approve_break_glass($bg2['id'],2);update_user_meta(2,'_smc_continuity_state_v1',['state'=>'dormant']);$current_user_id=1;t('break-glass rejects stale privileged approval at consume',is_array($bg2)&&$ap===true&&SMC_Advanced_Trust_2026::consume_break_glass($bg2['id'],1)===false);delete_user_meta(2,'_smc_continuity_state_v1');unset($filters['smc_file02_authentication_assurance_v1']);
// R2: age/jurisdiction is recomputed from current canonical application data at assertion time, not only by cron.
$apps[11]=['date_of_birth_enc'=>gmdate('Y-m-d',strtotime('-10 years')),'gender'=>'male','residence_country'=>'PK'];$m=SMC_Advanced_Trust_2026::minimal_assertions(11,'file20');t('under-minimum current age is denied synchronously',empty($m['age_requirement_met']));$apps[11]['date_of_birth_enc']=gmdate('Y-m-d',strtotime('-20 years'));$m=SMC_Advanced_Trust_2026::minimal_assertions(11,'file20');t('adult current age passes synchronous age gate',!empty($m['age_requirement_met']));
$fail=0;foreach($T as [$n,$ok]){echo ($ok?'PASS ':'FAIL ').$n."\n";if(!$ok)$fail++;}echo 'Fifth fresh runtime: '.(count($T)-$fail).' PASS / '.$fail." FAIL\n";exit($fail?1:0);
