<?php
declare(strict_types=1);
define('ABSPATH',__DIR__.'/'); define('ARRAY_A','ARRAY_A');
define('SMC_FILE01_AUTH_CLAIM_VERSION','1.0.0'); define('SMC_FILE01_FOUNDATION_CONTRACT_VERSION','2.0.0');
class WP_User{public $ID;public $allcaps;function __construct($id,$caps=[]){$this->ID=$id;$this->allcaps=$caps;}}
class WP_Error{}
class SMC_Security{public static function decrypt($v,$p,$c=[]){return $v;}}
class SMC_Contracts{public static function assertions($id){return $GLOBALS['assertions'][$id]??[];} public static function requested_types($id){return ['member'];}}
$GLOBALS['current']=1; $GLOBALS['users']=[]; $GLOBALS['assertions']=[]; $GLOBALS['states']=[]; $GLOBALS['founder']=1;
function absint($v){return abs((int)$v);} function sanitize_key($v){return strtolower(preg_replace('/[^a-z0-9_\-]/','',(string)$v));} function get_current_user_id(){return $GLOBALS['current'];}
function get_userdata($id){return $GLOBALS['users'][$id]??false;} function user_can($u,$cap){$id=is_object($u)?$u->ID:(int)$u;return !empty($GLOBALS['users'][$id]->allcaps[$cap]);}
function smc_is_founder($id){return (int)$id===(int)$GLOBALS['founder'];} function smc_is_institutional_account($id){return !empty($GLOBALS['assertions'][$id]['institutional_account']);}
function smc_membership_state($id){return $GLOBALS['states'][$id]??['status'=>'approved'];} function smc_application($id){return ['date_of_birth_enc'=>'age:30','gender'=>'male','residence_country'=>'PK'];}
function smc_age_from_dob($v){return 30;} function smc_effective_minimum_age($g,$c=''){return 15;} function smc_professional_types(){return ['doctor'];} function is_wp_error($v){return $v instanceof WP_Error;}
function wp_generate_uuid4(){static $n=0;return sprintf('00000000-0000-4000-8000-%012d',++$n);} function apply_filters($t,$v,...$a){return $v;} function wp_doing_cron(){return false;} function is_user_logged_in(){return true;} function is_admin(){return true;} function smc_is_membership_page(){return false;}
function add_action(...$a){} function remove_action(...$a){} function add_filter(...$a){} function remove_filter(...$a){} function __($s,$d=''){return $s;} function esc_html__($s,$d=''){return $s;} function wp_unslash($v){return $v;}
require dirname(__DIR__).'/source/sabri-membership-core/includes/class-smc-authorization.php';
$fail=[];$pass=0;function ok($c,$n){global $fail,$pass;if($c)$pass++;else$fail[]=$n;}
function usercase($id,$admin,$eligible=true,$hard=false,$founder=false){$GLOBALS['users'][$id]=new WP_User($id,$admin?['manage_options'=>true]:[]);$GLOBALS['assertions'][$id]=['institutional_account'=>$admin||$founder,'eligible'=>$eligible,'hard_blocked'=>$hard,'guardian_verified'=>true,'email_verified'=>true,'phone_verified'=>true,'status'=>$hard?'suspended':'approved'];$GLOBALS['states'][$id]=['status'=>$hard?'suspended':'approved'];if($founder)$GLOBALS['founder']=$id;}
function req($id,$action,$cap,$purpose=null,$contract='2.0.0',$hash=null){return ['user_id'=>$id,'actor_id'=>$id,'action'=>$action,'capability'=>$cap,'object_hash'=>$hash?:str_repeat('a',64),'purpose'=>$purpose?:$action,'plugin'=>'file-01','contract'=>$contract,'current_time'=>time()];}
usercase(1,true,true,false,true); usercase(2,true,true,false,false); usercase(3,false,true,false,false); usercase(4,true,false,true,true);
$GLOBALS['founder']=1;$GLOBALS['current']=1;$c=SMC_Authorization::file01_authorization_claim(null,req(1,'view','view_sabri_foundation'));ok(is_array($c)&&$c['allowed']===true&&$c['institutional_role']==='founder','Founder view allowed');ok($c['expires_at']-$c['issued_at']===60,'TTL 60 seconds');ok($c['plugin']==='file-01'&&$c['contract']==='2.0.0'&&$c['object_hash']===str_repeat('a',64),'claim bindings preserved');
$GLOBALS['current']=2;$c=SMC_Authorization::file01_authorization_claim(null,req(2,'view','view_sabri_foundation'));ok($c['allowed']===true&&$c['institutional_role']==='administrator','Administrator view allowed');$c=SMC_Authorization::file01_authorization_claim(null,req(2,'run_system_check','manage_sabri_foundation'));ok($c['allowed']===true,'Administrator persistent System Check allowed');$c=SMC_Authorization::file01_authorization_claim(null,req(2,'record_release','release_sabri_foundation'));ok($c['allowed']===false,'Administrator release denied');
$GLOBALS['current']=1;$c=SMC_Authorization::file01_authorization_claim(null,req(1,'record_release','release_sabri_foundation'));ok($c['allowed']===true,'Founder release allowed');
$GLOBALS['current']=3;$c=SMC_Authorization::file01_authorization_claim(null,req(3,'view','view_sabri_foundation'));ok($c['allowed']===false&&$c['institutional_role']==='member','ordinary member denied');
$GLOBALS['founder']=4;$GLOBALS['current']=4;$c=SMC_Authorization::file01_authorization_claim(null,req(4,'view','view_sabri_foundation'));ok($c['allowed']===false,'hard-blocked Founder denied');
$GLOBALS['current']=2;ok(null===SMC_Authorization::file01_authorization_claim(null,req(2,'view','manage_sabri_foundation')),'capability mismatch rejected');ok(null===SMC_Authorization::file01_authorization_claim(null,req(2,'view','view_sabri_foundation',null,'9.9.9')),'contract mismatch rejected');ok(null===SMC_Authorization::file01_authorization_claim(null,req(2,'view','view_sabri_foundation',null,'2.0.0','bad')),'bad object hash rejected');$r=req(2,'view','view_sabri_foundation');$r['actor_id']=99;ok(null===SMC_Authorization::file01_authorization_claim(null,$r),'actor mismatch rejected');$r=req(2,'View','view_sabri_foundation');ok(null===SMC_Authorization::file01_authorization_claim(null,$r),'noncanonical action rejected');$r=req(2,'view','view_sabri_foundation');$r['current_time']=time()-121;ok(null===SMC_Authorization::file01_authorization_claim(null,$r),'stale request rejected');$existing=['allowed'=>false];ok(SMC_Authorization::file01_authorization_claim($existing,req(2,'view','view_sabri_foundation'))===$existing,'existing provider result preserved');
if($fail){foreach($fail as $f)fwrite(STDERR,"FAIL: $f\n");exit(1);}echo "file01 auth bridge runtime: $pass PASS / 0 FAIL\n";
