<?php
error_reporting(E_ALL);
define('ABSPATH', __DIR__ . '/'); define('MINUTE_IN_SECONDS',60); define('DAY_IN_SECONDS',86400); define('YEAR_IN_SECONDS',31536000);
$meta=[];$filters=[];$current_user_id=1;
class WP_Error{public $code;function __construct($c,$m=''){$this->code=$c;}} function is_wp_error($v){return $v instanceof WP_Error;} function __($s,$d=null){return $s;} function absint($v){return abs((int)$v);} function sanitize_key($v){return strtolower(preg_replace('/[^a-z0-9_\-]/','',(string)$v));} function sanitize_text_field($v){return trim(strip_tags((string)$v));}
function get_userdata($id){return $id>0?(object)['ID'=>$id]:false;} function get_user_meta($id,$key='',$single=false){global $meta;return $meta[$id][$key]??($single?'':[]);} function update_user_meta($id,$key,$v){global $meta;$meta[$id][$key]=$v;return true;} function delete_user_meta($id,$key){global $meta;unset($meta[$id][$key]);return true;} function metadata_exists($type,$id,$key){global $meta;return array_key_exists($key,$meta[$id]??[]);} function get_current_user_id(){global $current_user_id;return $current_user_id;} function current_user_can($c){return true;} function user_can($u,$c){return true;}
function add_filter($t,$c,$p=10,$n=1){return true;} function add_action($t,$c,$p=10,$n=1){return true;} function apply_filters($tag,$value,...$args){global $filters;return isset($filters[$tag])?$filters[$tag]($value,...$args):$value;} function do_action($t,...$a){} function wp_generate_uuid4(){return '00000000-0000-4000-8000-000000000001';} function wp_salt($s='auth'){return 'salt';} function wp_json_encode($v,$f=0){return json_encode($v,$f);} function get_option($k,$d=false){return $d;} function update_option($k,$v,$a=false){return true;} function add_option($k,$v,$d='',$a='yes'){return true;} function delete_option($k){return true;} function get_users($a=[]){return [];} function smc_is_founder($id){return (int)$id===1;} function smc_is_institutional_ai($id){return false;}
class WPDBV2{public $prefix='wp_';public $users='wp_users';function prepare($q,...$a){return $q;}function get_var($q){return null;}function get_col($q){return [];}} $wpdb=new WPDBV2();
class SMC_Security{public static $verified=false;static function session_is_verified($id){return self::$verified;}static function session_verified_at($id){return self::$verified?time()-30:0;}static function subject_hash($id){return hash('sha256',(string)$id);}static function audit($a,$id=0,$d=[]){return true;}static function revoke_all_sessions($id,$r=''){return true;}}
class SMC_Contracts{static function assertions($id){return ['identity_documents_current'=>true,'phone_verified'=>true,'email_verified'=>true,'guardian_verified'=>true,'professional_verified'=>true,'approved'=>true,'suspended'=>false,'eligible'=>true];}} class SMC_CF01_Contract{static function ensure_subject_uuid($id){return 'uuid-'.$id;}}
require __DIR__.'/../source/sabri-membership-core/includes/class-smc-advanced-trust-2026.php';
$tests=[];function t($n,$ok){global $tests;$tests[]=[$n,(bool)$ok];}
$v2good=fn($base,$uid)=>['owner'=>'file02','contract_version'=>'2.0.0','level'=>3,'method'=>'passkey','verified_at'=>time()-30,'risk'=>'normal','user_verified'=>true,'phishing_resistant'=>true,'session_bound'=>true,'fingerprint_bound'=>true,'passkey_asserted'=>true,'hardware_backed'=>true];
$filters['smc_file02_authentication_assurance_v2']=$v2good;
$a=SMC_Advanced_Trust_2026::authentication_assurance(7);t('v2 accepted',$a['owner']==='file02'&&$a['contract_version']==='2.0.0'&&$a['level']===3&&$a['phishing_resistant']&&$a['session_bound']&&$a['fingerprint_bound']);
$p=SMC_Advanced_Trust_2026::assurance_profile(7);t('v2 provenance propagated',$p['authentication_contract_version']==='2.0.0'&&$p['phishing_resistant']&&$p['user_verified']);
$r=SMC_Advanced_Trust_2026::step_up_requirement(7,'break_glass');t('break glass requires phishing resistance',$r['phishing_resistant_required']===true&&$r['satisfied']===true);
$rm=new ReflectionMethod('SMC_Advanced_Trust_2026','actor_meets_step_up');$rm->setAccessible(true);t('v2 satisfies stepup without duplicate local MFA gate',$rm->invoke(null,1,'break_glass','manage_options',true)===true);
$filters['smc_file02_authentication_assurance_v2']=fn($b,$u)=>['owner'=>'file02','contract_version'=>'2.0.0','level'=>4,'verified_at'=>time()-20,'session_bound'=>false,'fingerprint_bound'=>true];$filters['smc_file02_authentication_assurance_v1']=fn($b,$u)=>['owner'=>'file02','contract_version'=>'1.0.0','level'=>3,'verified_at'=>time()-10,'passkey_asserted'=>true,'hardware_backed'=>true];$a=SMC_Advanced_Trust_2026::authentication_assurance(7);t('malformed v2 cannot downgrade to v1',$a['owner']==='file00');unset($filters['smc_file02_authentication_assurance_v2']);$a=SMC_Advanced_Trust_2026::authentication_assurance(7);t('v1 compatibility retained',$a['owner']==='file02'&&$a['contract_version']==='1.0.0');
$filters['smc_file02_authentication_assurance_v2']=fn($b,$u)=>['owner'=>'file02','contract_version'=>'2.0.0','level'=>3,'method'=>'passkey','verified_at'=>time()-20,'risk'=>'high','user_verified'=>true,'phishing_resistant'=>false,'session_bound'=>true,'fingerprint_bound'=>true,'passkey_asserted'=>true,'hardware_backed'=>true];$r=SMC_Advanced_Trust_2026::step_up_requirement(7,'profile_sensitive_change');t('v2 high risk strengthens native stepup',$r['risk_context']['high_risk']===true&&$r['required_authentication_level']>=3&&$r['phishing_resistant_required']===true&&$r['satisfied']===false);
// ROUND8_TESTS_DONE
// ROUND9_TESTS
$fail=0;foreach($tests as[$n,$ok]){echo($ok?'PASS ':'FAIL ').$n."\n";if(!$ok)$fail++;}echo 'File02 assurance v2 runtime: '.(count($tests)-$fail).' PASS / '.$fail." FAIL\n";exit($fail?1:0);
